server:
  port: ${PORT:31001}
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:root@47.114.157.42:27017
      database: xc_cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 47.114.157.42
    username: gakki
    password: gakki
    virtual-host: /
    port: 5672
eureka:
  client:
    fetch-registry: true #服务发现，是否从eureka中获取注册信息
    register-with-eureka: true #服务注册，是否将自己注册到eureka服务中
    service-url: #客户端和服务端交互地址
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:50101/eureka/}
  instance:
    prefer-ip-address: true #将自己的ip地址注册到eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id