server:
  port: ${PORT:50101}
spring:
  application:
    name: xc-govern-center
eureka:
  client:
    fetch-registry: false #服务发现，是否从eureka中获取注册信息
    register-with-eureka: false #服务注册，是否将自己注册到eureka服务中
    service-url: #客户端和服务端交互地址
      defaultZone: ${EUREKA_SERVER:http://eureka01:50101/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 6000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01}