server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:root@47.114.157.42:27017
      database: xc_cms
  rabbitmq:
    username: gakki
    password: gakki
    host: 47.114.157.42
    virtual-host: /
xuecheng:
  mq:
  #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    routingkey: 5a751fab6abb5044e0d19ea1